version: '3.7'

services:
  php-fpm:
    build: ./images/php
    links:
      - db
    volumes:
      - ./images/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html:delegated
    command: bash -c "php-fpm"
  nginx-app:
    image: nginx
    ports:
      - 9001:80
    links:
      - php-fpm
    volumes:
      - ./images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:delegated
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    healthcheck:
      test: bash -c "</dev/tcp/db/3306 $$ exit 0 || exit 1"
      interval: 3s
      timeout: 90s
      retries: 30
    volumes:
      - ./images/db/.mytop:/root/.mytop:ro
      - ./images/db/my.cnf:/etc/mysql/my.cnf:ro
      - ./images/db/my.cnf:/usr/local/etc/my.cnf:ro
      - ./images/db/my.cnf:/etc/mysql/mysql.conf.d/my.cnf:ro
      - ./images/db/my.cnf:/etc./my.cnf:ro
  frontend-main:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html:delegated
    working_dir: /var/www/html
    command: bash -c "npm install && npm run dev"
